// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/kislerdm/pulumi-sdk-neon/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Neon API token.
func GetApi_key(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "neon:api_key")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "NEON_API_KEY"); d != nil {
		value = d.(string)
	}
	return value
}
